pyweb/auction/urls.py
from django.conf.urls import patterns, url

from auction import views

urlpatterns = patterns('', 
        url(r'^$', views.index, name='index'), 
        url(r'^bill/', views.bill, name='bill' ),
        url(r'^winners/', views.winners, name='winners' ),
)

pyweb/pyweb/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pyweb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^auction/', include('auction.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'auction.views.index', name='index'),
)

pyweb/auction/models.py
from django.db import models

# Create your models here.

from django.db import models

class Customer(models.Model):
    paddle_number = models.IntegerField(unique=True)
#    access_code = models.IntegerField()
    name = models.CharField(max_length=255)
    email = models.EmailField(null=True, blank=True)
    paid = models.BooleanField(help_text="This will be checked automatically during checkout", default=False)
    paid_amount = models.DecimalField(max_digits=7,decimal_places=2, null = True, blank = True, help_text="Leave this field blank if paid in full ")
    modified_time = models.DateTimeField(auto_now = True)
    PAYMENT_METHODS = ( ('CASH', 'Cash'), ('CHECK', 'Check'), ('CREDITCARD', 'CreditCard'), ('OTHER', 'Other'),)
    payment_method = models.CharField(max_length=10, choices=PAYMENT_METHODS, null = True, blank= True, help_text = "Select a payment method during checkout")
    email_receipt = models.BooleanField(default=False)
    def __unicode__(self):
        return "%s %s" % (self.paddle_number, self.name)
    class Meta:
        ordering = ['paddle_number']

class Item(models.Model):
    bid_number = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    max_winner = models.IntegerField(default = 1)
    TYPES = ( ('SILIENT', 'Slient Auction'), ('LIVE', 'Live Auction'),  ('OTHER', 'Other'),)
    type = models.CharField(max_length = 10, choices = TYPES);
    created_time = models.DateTimeField(auto_now_add = True)
    modified_time = models.DateTimeField(auto_now = True)
    def __unicode__(self):
        return "%s (%s)" % (self.name, self.bid_number)
    class Meta:
        ordering = ['bid_number']
   
class Transaction(models.Model):
    customer = models.ForeignKey(Customer)
    item = models.ForeignKey(Item)
    price = models.DecimalField(max_digits=7,decimal_places=2)
    created_time = models.DateTimeField(auto_now_add = True)
    modified_time = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ['customer__paddle_number']
    def __unicode__(self):
        return "%s(%d) purchased %s(%s) at %f" % (self.customer.name, self.customer.paddle_number, self.item.name, self.item.bid_number, self.price)

pyweb/auction/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.db.models import Count, Min, Sum, Avg

# Create your views here.

from django.http import HttpResponse
from auction.models import Customer, Item, Transaction
#from auction.forms import CheckoutForm
def index(request):
    if request.POST:
        try:
            c = Customer.objects.get(paddle_number=request.POST['pn'])
        except :
            return HttpResponse("Invalid paddle number");
        transactions = c.transaction_set.all()
        if transactions:
            transaction_sum = c.transaction_set.aggregate(Sum('price'))['price__sum']
        else:
            transaction_sum = 0
        return render(request, 'auction/simplebill.html', {'customer':c, 'transactions': transactions, 'transaction_sum': transaction_sum})

    else:
        return render(request,'auction/index.html')


    
def bill(request):
    if 'id' in request.GET:
        c = Customer.objects.get(pk=request.GET['id'])
        transactions = c.transaction_set.all()
        if transactions:
            transaction_sum = c.transaction_set.aggregate(Sum('price'))['price__sum']
        else:
            transaction_sum = 0
        if not c.paid_amount :
            return HttpResponse("Cannot checkout as paid amount is zero.")

        return render(request, 'auction/bill.html', {'customer':c, 'transactions': transactions, 'transaction_sum': transaction_sum, 'balance': transaction_sum - c.paid_amount})
    else:
        return HttpResponse( "id not found");


def winners(request):
    return render(request, 'auction/winners.html', {'transactions': Transaction.objects.filter(item__type='SILIENT').order_by('customer__paddle_number') } )

pyweb/auction/templates/auction/bill.html
{% load humanize %}
<html>
	<head>
		<title>Acton Barn Cooperative 2016 Spring Auction</title>
		<style>
			@media print {
				button { display: none}
			}
			@media screen {
				button { font-size: 36px;
					margin: 5px 10px 5px 10px;
				}
			}
			@media screen, print{
				body { background:white; color:black; margin:36px }
			   	p {font-size:20px;}
				table, th, td
				{
					border: 1px solid green;
				}
				table
				{
					border-collapse:collapse;
				}
				th, td
				{
					border:1px solid gray;
					padding:3px 7px 2px 7px;
				}
				tr.row1 td 
				{
					color:#000000;
					background-color:#EAF2D3;
				}
				img {

					float:right;
				}
				h1 {

					font-size: 24px;
				}
			}
		</style>
	</head>
	<body>
		<img width="80px" height="80px" src="/static/auction/logo.jpg" />
		<h1>Acton Barn Cooperative Nursery School</h1>
		<h2>2016 Spring Auction</h2>
	<table width ="100%" />
		<tr>
			<th>Name</th>
			<th>Paddle Number</th>
		</tr>
		<tr>
			<td>{{customer.name}} </td>
			<td>{{customer.paddle_number }} </td>
		</tr>

		<tr>
			<th>Payment Method</th>
			<th>Date</th>
		</tr>
		<tr>
			<td>{{customer.payment_method}} </td>
			<td>  {% now "F jS, Y" %}</td>
		</tr>
	</table>

	<h3>Purchase Records: </h2>
	<table width="100%" >
	<tr>
		<th width="20%">Bid Number</th> 
		<th width="60%">Item </th> 
		<th width="20%" >Price</th> 
	</tr>
	{% for t in transactions %}
	<tr class="{% cycle 'row1' 'row2' %}">
		<td class="field-xx">{{ t.item.bid_number }} </td>
		<td>{{ t.item.name }} </td>
		<td>${{ t.price|floatformat:2|intcomma }} </td>
	</tr>
	{% endfor %}
	<tr> 
		<td colspan="2"><strong>Total</strong></td>
		<td><strong>${{transaction_sum|floatformat:2|intcomma }}</strong> </td>
	</tr>

	<tr> 
		<td colspan="2"><strong>Paid</strong></td>
		<td><strong>${{customer.paid_amount|floatformat:2|intcomma }}</strong> </td>
	</tr>
	{% if balance >= 0  %}
	<tr> 
		<td colspan="2"><strong>Balance</strong></td>
		<td><strong>${{ balance |floatformat:2|intcomma }}</strong> </td>
	</tr>
	{% endif %}
	</table>
	<p>Thanks for your support!</p>
	<p><small>We are a 501(c)3 organization. Our non-profit tax identification number is E 042 526 055.</small></p>
	<button  onclick="javascript:window.print()" > Print </button> 
	<button  onclick="javascript:window.close()" > Close </button>
	</body>

</html>

pyweb/auction/templates/auction/bill.pdf.html
{% load humanize %}
{% autoescape off %}
<html>
	<body>
		<img width="80" height="80" src="logo.jpg" />
		<h1>Acton Barn Cooperative Nursery School</h1>
		<h2>2016 Spring Auction</h2>

		<h4>Paddle#:     {{customer.paddle_number}}                             Name:     {{customer.name}}</h4>

	<h3>Purchase Records: </h3>

	<ul>

	{% for t in transactions %}
	<li><font face="Courier"> {{t}} </font></li>
	{% endfor %}
	</ul> 
	<p />
	<h3>Payment </h3>
	<ul>
		<li><font face="Courier"> {{sum}}</font></li>
	{% if balance_num < 0  %}
		<li><font face="Courier"> {{extra}}</font></li>
	{% endif %}
		<li><font face="Courier"> {{paid}}</font></li>
	{% if balance_num > 0  %}
		<li><font face="Courier"> {{balance}}</font></li>
	{% endif %}
	
	</ul>
	<p />
	<p><font>Paid by {{customer.payment_method}} on {{ when_datetime|date:"F jS, Y" }}, Thanks for your support!</font></p>
	<p />
	<p><font size="11">We are a 501(c)3 organization. Our non-profit tax identification number is E 042 526 055.</font></p>
	</body>

</html>

    {% endautoescape %}

pyweb/auction/templates/auction/change_form.html
{% extends "admin/change_form.html" %}
{% block after_field_sets %}
{% if transaction_sum %}
{% load humanize %}

<div class="inline-group" >
<div class="tabular inline-related ">
<h2> Purchase Records: </h2>
<table width="100%" >
	<tr>
		<th width="20%">Bid Number</th> 
		<th width="60%">Item </th> 
		<th width="20%" >Price</th> 
	</tr>
	{% for t in transactions %}
	<tr>
		<td class="field-xx">{{ t.item.bid_number }} </td>
		<td>{{ t.item.name }} </td>
		<td>${{ t.price|floatformat:2|intcomma }} </td>
	</tr>
	{% endfor %}
	<tr> 
		<td colspan="2"><strong>Total<strong></td>
		<td><strong> ${{transaction_sum|floatformat:2|intcomma }} <input type="hidden" id="total_due" value="{{transaction_sum}}" /><strong></td>
	</tr>
</table>
</div>
</div>
{% endif %}

{% endblock %}

{% block submit_buttons_bottom %}

{% load i18n admin_urls %}

<div class="submit-row">
	<input type="submit" value="{% trans 'Save' %}" class="default" name="_save" />
	<input id="checkoutButton" type="submit" value="{% trans 'Checkout' %}" name="_checkout" />
	<input id="printButton" type="Button" value="{% trans 'Print' %}" name="_print" />
</div>

{% endblock %}

{% block extrahead %}
{{block.super}}
	
 <script type="text/javascript">
	 var $ = django.jQuery;
	 $( document ).ready(function() {
			 $("#checkoutButton").click(function(e){
				 if(!$("#id_payment_method").val()) {
				 	alert("Please select a payment method");
					e.preventDefault();
					return;
				 }	
				 if(!$("#id_paid_amount").val()){
				 	//alert("Set paid amount to total due " + $("#total_due").val());
					$("#id_paid_amount").val($("#total_due").val());
				 }


				 $("#id_paid").prop("checked","checked");
				 $("#customer_form").submit();
				 }); 
			 $("#printButton").click(function(){
					window.open("/auction/bill?id={{original.id}}", "Checkout" , "height=1024,width=768");
			 });


			{%if request.GET.show_print %}
				$("#printButton").show();
			{%else %}

				$("#printButton").hide();
			{%endif%}

			 });
</script>
{% endblock %}

pyweb/auction/templates/auction/index.html
<html>
	<body>
		<form action="#" method="POST">
			Paddle Number: <input name="pn">
			 {% csrf_token %}
			<input type="submit" />
		</form>
	<body>
	</html>

pyweb/auction/templates/auction/item_change_form.html
{% extends "admin/change_form.html" %}

{% block extrahead %}
{{block.super}}
	
 <style>
	 .add-another {
		 display:none
	 }
</style>
{% endblock %}

pyweb/auction/templates/auction/simplebill.html
{% load humanize %}
<html>
	<head>
		<title>Acton Barn Cooperative 2016 Spring Auction</title>
		<style>
			@media print {
				button { display: none}
			}
			@media screen {
				button { font-size: 36px;
					margin: 5px 10px 5px 10px;
				}
			}
			@media screen, print{
				body { background:white; color:black; margin:36px }
			   	p {font-size:20px;}
				table, th, td
				{
					border: 1px solid green;
				}
				table
				{
					border-collapse:collapse;
				}
				th, td
				{
					border:1px solid gray;
					padding:3px 7px 2px 7px;
				}
				tr.row1 td 
				{
					color:#000000;
					background-color:#EAF2D3;
				}
				img {

					float:right;
				}
				h1 {

					font-size: 24px;
				}
			}
		</style>
	</head>
	<body>
		<img width="80px" height="80px" src="/static/auction/logo.jpg" />
		<h1>Acton Barn Cooperative Nursery School</h1>
		<h2>2016 Spring Auction</h2>
	<table width ="100%" />
		<tr>
			<th>Paddle Number</th>
		</tr>
		<tr>
			<td>{{customer.paddle_number }} </td>
		</tr>
	</table>

	<h3>Purchase Records: </h2>
	<table width="100%" >
	<tr>
		<th width="20%">Bid Number</th> 
		<th width="60%">Item </th> 
		<th width="20%" >Price</th> 
	</tr>
	{% for t in transactions %}
	<tr class="{% cycle 'row1' 'row2' %}">
		<td class="field-xx">{{ t.item.bid_number }} </td>
		<td>{{ t.item.name }} </td>
		<td>${{ t.price|floatformat:2|intcomma }} </td>
	</tr>
	{% endfor %}
	<tr> 
		<td colspan="2"><strong>Total</strong></td>
		<td><strong>${{transaction_sum|floatformat:2|intcomma }}</strong> </td>
	</tr>

	</table>
	<strong>Note: It may take a while for the operator to input all bid records, the above result may be incomplete or inaccurate.</strong>
	<p>Thanks for your support!</p>
	<button  onclick="javascript:history.go(-1)" > Back </button>
	</body>

</html>

pyweb/auction/templates/auction/transaction_change_list.html
{% extends "admin/change_list.html" %}
{% load i18n admin_urls admin_static admin_list %}
{% block content %}
  {{ block.super }}
  <div class="results" id="admin-div">
  <h2>Statistics</h2>
  <table width = "100%">
	  <tr>
		  <th>Total Transaction Amount</th>
		  <th>Total Transaction Count</th>
		  <th>&nbsp;</th>
	  </tr>
	  <tr>
		  <td>{{TransactionAmount}}</td>
		  <td>{{TransactionCount}}</td>
		  <td>&nbsp;</td>

	  </tr>
	  <tr>
		  <th>Total Customer Paid Amount</th>
		  <th>Total Customer Count</th>
		  <th>Total Customer Paid Count</th>
	  </tr>
	  <tr>
		  <td>{{CustomerPaidAmount}}</td>
		  <td>{{CustomerCount}}</td>
		  <td>{{CustomerPaidCount}}</td>
	  </tr>

	  <tr>
		  <th>Total Customer Paid In Cash</th>
		  <th>Total Customer Paid In Check</th>
		  <th>Total Customer Paid In CreditCard</th>
	  </tr>
	  <tr>
		  <td>{{CustomerCashPaidAmount}}</td>
		  <td>{{CustomerCheckPaidAmount}}</td>
		  <td>{{CustomerCreditCardPaidAmount}}</td>
	  </tr>

	  <tr>
		  <th>Total Customer Paid In Other</th>
		  <th>-</th>
		  <th>-</th>
	  </tr>
	  <tr>
		  <td>{{CustomerOtherPaidAmount}}</td>
		  <td>-</td>
		  <td>-</td>
	  </tr>
  </table>
  </div>

  <button class="hide" onclick="javascript:window.print(); ">Print</button>
  <button class="hide" onclick="javascript:showstatistics(django.jQuery);window.print(); ">Print Statistics</button>
{% endblock %}
{% block extrahead %}

  {{ block.super }}
  <script type="text/javascript">
	function hide($){
		$("#admin-div").addClass("hide");
		$(".object-tools").addClass("hide");
		$("#toolbar").addClass("hide");
		$(".actions").addClass("hide");
		$("#user-tools").addClass("hide");
		$("#changelist-filter").addClass("hide");
	}
	var $ = django.jQuery;
	$( document ).ready(function() {
			hide($);
	});
	function showstatistics($){
		$("#content-main").addClass("hide");
		$("#admin-div").removeClass("hide");
	}

  </script>

{% endblock %}
{% block extrastyle %}
  {{ block.super }}
<style>
	@media print{
	#header {
		display: none;
	}
	#toolbar {
		display: none;
	}
	.hide{
		display: none;
	}
	.show{
		display: inline;
	}
	}
</style>

{% endblock %}

pyweb/auction/templates/auction/winners.html
{% load humanize %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Barn Auction Winners</title>

    <style>
table, th, td
{
  border-collapse:collapse;
  border: 1px solid black;
  padding: 5px;
}
    </style>

  </head>
<body>

<h2>2016 Barn Silent Auction Winners</h2>

<table>
<tr>
  <th>Item</th><th>Item Name</th><th>Winning Paddle Number</th><th>Amount</th>
</tr>

{% for transaction in transactions %}
<tr>
  <td>{{ transaction.item.bid_number }}</td>
  <td>{{ transaction.item.name }}</td>
  <td style="text-align: right;">{{ transaction.customer.paddle_number }}</td>
  <td style="text-align: right;">${{ transaction.price | floatformat:2 | intcomma }}</td>
</tr>
{% endfor %}

</table>

</body>
</html>